export const CLOSE_MODAL = 'close_modal'
export const SELECT_NEWS = 'select_news'
export const MODAL_CONTENT = 'modal_content'
export const FETCH_NEWS = 'fetch_news'
export const FETCH_NEWS_FACULTY = 'fetch_news_faculty'
export const ADD_FAVORITE_NEWS = 'add_favorite_news'
export const CHECK_FAVORITE_NEWS = 'check_favorite_news'